apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: $1
  namespace: $2
  labels:
    app: $1
spec:
  replicas: $3
  selector:
    matchLabels:
      app: $1
  template:
    metadata:
      labels:
        app: $1
    spec:
      containers:
      - name: $1
        image: $4
        resources:
          limits:
            cpu: $5
            memory: $6
          requests:
            cpu: $5
            memory: $6
        ports:
        - containerPort: $8
          protocol: TCP